name: Flutter Tests

on:
  push:
    branches: [ "main", "develop", "feature/**" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codigo
        uses: actions/checkout@v4

      - name: Configurar Flutter (stable)
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Ver version de Flutter
        run: flutter --version

      - name: Instalar dependencias
        run: flutter pub get

      - name: Correr tests
        run: flutter test
